create table if not exists public.avdb_stage_runs (
  id uuid primary key default gen_random_uuid(),
  source text not null default 'avdbapi',
  status text not null default 'queued' check (status in ('queued','running','paused','completed','failed','cancelled')),
  start_page integer not null check (start_page >= 1),
  end_page integer not null check (end_page >= start_page),
  current_page integer not null,
  checkpoint_page integer,
  concurrency integer not null default 1 check (concurrency between 1 and 3),
  retry_limit integer not null default 2 check (retry_limit between 0 and 5),
  pages_scanned integer not null default 0 check (pages_scanned >= 0),
  items_discovered integer not null default 0 check (items_discovered >= 0),
  items_staged integer not null default 0 check (items_staged >= 0),
  duplicates_found integer not null default 0 check (duplicates_found >= 0),
  player_ready integer not null default 0 check (player_ready >= 0),
  published_count integer not null default 0 check (published_count >= 0),
  failed_count integer not null default 0 check (failed_count >= 0),
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz,
  paused_at timestamptz,
  resumed_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.avdb_stage_items (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.avdb_stage_runs(id) on delete set null,
  source text not null default 'avdbapi',
  source_page integer,
  source_page_url text,
  api_url text,
  external_id text,
  movie_code text,
  title text not null default '',
  original_title text,
  slug text,
  year text,
  quality text,
  duration text,
  description text,
  poster_url text,
  thumb_url text,
  player_page_url text,
  player_provider text,
  player_status text not null default 'unverified' check (player_status in ('unverified','checking','ready','failed','blocked')),
  stage_status text not null default 'discovered' check (stage_status in ('discovered','staged','duplicate','player_check','player_ready','published','error')),
  dedupe_key text,
  duplicate_of uuid references public.avdb_stage_items(id) on delete set null,
  last_error text,
  raw_data jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.avdb_stage_logs (
  id bigint generated by default as identity primary key,
  run_id uuid references public.avdb_stage_runs(id) on delete cascade,
  level text not null default 'info' check (level in ('debug','info','warn','error','success')),
  step text not null default 'system',
  message text not null,
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists avdb_stage_runs_status_created_idx on public.avdb_stage_runs(status, created_at desc);
create index if not exists avdb_stage_items_run_status_idx on public.avdb_stage_items(run_id, stage_status, updated_at desc);
create index if not exists avdb_stage_items_code_idx on public.avdb_stage_items(movie_code) where movie_code is not null;
create index if not exists avdb_stage_items_dedupe_idx on public.avdb_stage_items(dedupe_key) where dedupe_key is not null;
create unique index if not exists avdb_stage_items_external_unique on public.avdb_stage_items(source, external_id) where external_id is not null;
create index if not exists avdb_stage_logs_run_created_idx on public.avdb_stage_logs(run_id, created_at desc);

alter table public.avdb_stage_runs enable row level security;
alter table public.avdb_stage_items enable row level security;
alter table public.avdb_stage_logs enable row level security;

revoke all on table public.avdb_stage_runs from anon, authenticated;
revoke all on table public.avdb_stage_items from anon, authenticated;
revoke all on table public.avdb_stage_logs from anon, authenticated;

grant select, insert, update, delete on table public.avdb_stage_runs to service_role;
grant select, insert, update, delete on table public.avdb_stage_items to service_role;
grant select, insert, update, delete on table public.avdb_stage_logs to service_role;
grant usage, select on sequence public.avdb_stage_logs_id_seq to service_role;
